---
driver:

provisioner:
  name: chef_solo

platforms:
  - name: vagrant-centos-7
    driver:
      name: vagrant
      box: centos-7
      box_url: 'https://github.com/holms/vagrant-centos7-box/releases/download/7.1.1503.001/CentOS-7.1.1503-x86_64-netboot.box'

suites:
  - name: default
    run_list: ['tc']
    attributes:
